name: Pyhton CI/CD with Maven

env:
  project_id: db-cicdpipeline-wave-3
on:
  push:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  BuildMaven:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: | 
        pytest

    - name: Build and Package
      run: |
        mvn clean package
        ls -lart target/*
        
    - name: publish artifact
      uses: actions/upload-artifact@v2
      with:
        path: target/*.zip
        name: Devops.zip
        
